default_language_version:
  python: python3.10
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-ast
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: debug-statements
      - id: end-of-file-fixer
      - id: name-tests-test
        args: ["--django"]
      - id: trailing-whitespace
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.252"
    hooks:
      - id: ruff
  - repo: https://github.com/pycqa/flake8
    rev: "" # pick a git hash / tag to point to
    hooks:
      - id: flake8
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
