# Generated by Django 4.1.7 on 2023-02-24 01:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_deposit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('value', models.FloatField(null=True)),
                ('public', models.BooleanField(default=False)),
                ('create_at', models.FloatField(default=django.utils.timezone.now)),
                ('destiny', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_destiny', to='resources.account')),
                ('origin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_origin', to='resources.account')),
            ],
        ),
    ]
