# Generated by Django 4.1.7 on 2023-02-24 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
