# Generated by Django 4.1.7 on 2023-02-24 02:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_transfer_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='create_at',
        ),
        migrations.AddField(
            model_name='transfer',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
